### ISSUE TITLE
Margin issue with toolbar and uxg-h6

### ISSUE THREAD

**Issue by xmonvoisin** [fusionfabric/finastra-design-system#69]
**Describe the bug**
uxg-h6 has a bottom margin of 16px which should be overriten by 0

**Comment by Romu-C** [comment]
This issue is about the breadcrumb in the toolbar. 
If you have this breadcrumb you will have margin on uxg-h6 class and you shouldn't.
```
<ul class="uxg-breadcrumb uxg-breadcrumb-responsive">
  <li>
    <a mat-flat-button class="uxg-h6">admin-portal</a>
  </li>
  <li>
    <a mat-flat-button>App Consent Management</a>
  </li>
</ul>
```
